# If not running interactively, don't do anything
[[ $- == *i* ]] || return
# case $- in
#     *i*) ;;
#       *) return;;
# esac

# echo "$( date +%T%z ) Begin sourcing .mac_zshrc..."

# --------------------------------------------------------------------
# Better directory navigation
# --------------------------------------------------------------------
# This defines where cd looks for targets
# Add the directories you want to have fast access to, separated by colon
# Ex: CDPATH=".:~:~/projects" will look for targets in the current working 
# directory, in home and in the ~/projects folder
CDPATH=".:~:/Users/caeadom/Documents/projects/"

[[ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]] \
    && source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# echo "$( date +%T%z ) End sourcing .mac_zshrc..."
