# echo "$( date +%T%z ) Begin sourcing .wsl_zshenv..."

# #######################################
# DEVELOPMENT SETTINGS
# #######################################
export REPO_BASE_DIR="/mnt/c/Users/caeadom/Documents/projects"
export DE_BASE_DIR="$REPO_BASE_DIR/de"
export WFM_BASE_DIR="$REPO_BASE_DIR/wfm"

# echo "$( date +%T%z ) End sourcing .wsl_zshenv..."
