truncate_to_repo = false
use_logical_path = true
fish_style_pwd_dir_length = 1
truncation_length = 10
truncation_symbol = "…/"

[git_status]
modified_count.enabled = true
untracked_count.enabled = true

